<?php

/**
 * Implements hook_theme().
 */
function sph_newsletter_theme($existing, $type, $theme, $path) {
  return [
    'newsletter__preview' => [
      'variables' => [
        'result' => NULL,
      ],
    ],
  ];
}

/**
 * Implement the hook_views_pre_render()
 */
function sph_newsletter_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if($view->id() == 'lifestyle_view'){
    // Get the node id from the URL
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface) {
      // You can get nid and anything else you need from the node object.
      $id = $node->id();
    }
    $config = \Drupal::config('queArticle.settings');
    foreach($view->result as $result){
      $nid = $result->_relationship_entities['field_queue_articles']->id();
      $entity_type = 'node';
      $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
      $node = $storage->load($nid);
      $title = $node->getTitle();
      $body = $node->field_subheadline->value;
      $node->title->value = !empty($config->get($id .'_'. $nid . '_title')) ? $config->get($id .'_'. $nid . '_title') : $title;
      $node->field_subheadline->value = !empty($config->get($id .'_'. $nid . '_body')) ? $config->get($id .'_'. $nid . '_body') : $body;
    }
  }
}


